name: Periodic health check

on:
  schedule:
    - cron: '5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://pokedex9377.onrender.com/
          follow-redirect: false 
          max-attempts: 3 
          retry-delay: 5s
          retry-all: false